---
title: "Interactive Maps"
sidebar: false
format:
  html: default
editor_options: 
  chunk_output_type: console
author: "Daniel Evans"
execute:
  warning: false
  
---

```{r,message=FALSE}
# data

library(tidyverse)
setwd("~")
PLACES <- read_csv("R/SDS264_F24/HW/Projects/Data/PLACES.csv")
AVG <- mean(PLACES$SLEEP_CrudePrev)

PLACES <- PLACES |>
  rename(name = StateDesc) |>
  group_by(name) |>
  summarize(
    depr = mean(DEPRESSION_CrudePrev), 
    sleep = mean(SLEEP_CrudePrev)
  ) |>
  ungroup() |>
  mutate(sleep = ifelse(sleep>AVG, "Above average", "Below average")) |>
  mutate(sleep = fct(sleep))
  

library(sf) 
states <- read_sf("https://rstudio.github.io/leaflet/json/us-states.geojson")


# joined
PLACES_states <- states |>
  left_join(PLACES, by = c("name" = "name"))

library(leaflet)
```


# First Map: Prevalence of Depression Across the United States

```{r}
# First

# bins
bins <- c(15, 17.5, 20, 22.5, 25, 27.5, 30)
pal <- colorBin("plasma", domain = PLACES_states$depr, bins = bins)

# labels
library(htmltools)
library(glue)

PLACES_states <- PLACES_states |>
  mutate(labels = str_c("<u>", name, "</u>: ", round(depr,2), "% prevalence"))

labels <- lapply(PLACES_states$labels, HTML)


# plot
leaflet(PLACES_states) |>
  setView(-96, 37.8, 4) |>
  addTiles(attribution = "Source: <a href='https://data.cdc.gov/500-Cities-Places/PLACES-Census-Tract-Data-GIS-Friendly-Format-2024-/yjkw-uj5s'>CDC PLACES</a>") |>
  addPolygons(
    fillColor = ~pal(depr),
    weight = 1,
    opacity = 1,
    color = "black",
    dashArray = "",
    fillOpacity = .9,
    highlightOptions = highlightOptions(
      weight = 5,
      color = "white",
      dashArray = "",
      fillOpacity = .5,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) |>
  addLegend(pal = pal, values = ~density, opacity = 0.7, title = "Prevalence of Depression",
    position = "bottomright")
```

# Second Map: Prevalence of Sleep Deprivation Across the United States

```{r}
# Second

# bins
pal <- colorFactor("magma", domain = PLACES_states$sleep, levels = c("Above average", "Below average"))

# labels
library(htmltools)
library(glue)

PLACES_states <- PLACES_states |>
  mutate(labels = str_c("<b>", name, "</b>: ", sleep, " prevalence of sleep deprivation"))

labels <- lapply(PLACES_states$labels, HTML)


# plot
leaflet(PLACES_states) |>
  setView(-96, 37.8, 4) |>
  addTiles(attribution = "Source: <a href='https://data.cdc.gov/500-Cities-Places/PLACES-Census-Tract-Data-GIS-Friendly-Format-2024-/yjkw-uj5s'>CDC PLACES</a>") |>
  addPolygons(
    fillColor = ~pal(sleep),
    weight = 1,
    opacity = 1,
    color = "darkgray",
    dashArray = "",
    fillOpacity = .6,
    highlightOptions = highlightOptions(
      weight = 3,
      color = "darkred",
      dashArray = "",
      fillOpacity = 1,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")) |>
  addLegend(pal = pal, values = PLACES_states$sleep, opacity = 0.7, 
          title = "Prevalence of Sleep Deprivation", position = "bottomright")
```
